defaults: &defaults
  default_tasks: ["Project Management", "Internal Meeting", "Customer Meeting",
                  "Design", "Development", "Documentation", "Sales"]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
